# Generated by Django 2.2.1 on 2019-05-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('nameRequest', models.CharField(max_length=100)),
                ('dateRequest', models.DateTimeField()),
                ('description', models.TextField()),
                ('signature', models.TextField()),
                ('image', models.ImageField(default='', upload_to='originals')),
                ('imageD', models.ImageField(default='', upload_to='portraits')),
                ('status', models.CharField(choices=[('C', 'In creation'), ('D', 'Delivered')], max_length=1)),
                ('cost', models.IntegerField(default=0)),
                ('dateDelivery', models.DateField(default='2018-05-15')),
            ],
        ),
    ]
