# Generated by Django 2.2 on 2019-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('nameRequest', models.CharField(max_length=100)),
                ('dateRequest', models.DateField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('C', 'In creation'), ('O', 'Waiting for the painter acceptance'), ('R', 'Rejected')], max_length=1)),
            ],
        ),
    ]
