# Generated by Django 2.2.1 on 2019-05-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoFactor',
        ),
    ]
