# Generated by Django 2.2 on 2019-05-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingrequest',
            name='image',
            field=models.ImageField(default='', upload_to='originals'),
        ),
    ]
