# Generated by Django 2.2.1 on 2019-05-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_twofactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingrequest',
            name='dateDelivery',
            field=models.DateField(default='2018-05-15'),
        ),
    ]
