# Generated by Django 2.2.1 on 2019-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190531_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingrequest',
            name='signatureP',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
