# Generated by Django 2.2 on 2019-05-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190521_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingrequest',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paintingrequest',
            name='dateDelivery',
            field=models.DateField(default=1995),
        ),
    ]
