# Generated by Django 2.2.1 on 2019-05-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_paintingrequest_datedelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingrequest',
            name='imageD',
            field=models.ImageField(default='', upload_to='portraits'),
        ),
    ]
