# Generated by Django 2.2 on 2019-05-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190521_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingrequest',
            name='dateDelivery',
            field=models.DateField(default='2019-12-12'),
        ),
    ]
