# Generated by Django 2.2 on 2019-05-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190521_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingrequest',
            name='dateDelivery',
            field=models.DateField(default=1995),
        ),
    ]
