# Generated by Django 2.2 on 2019-05-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190521_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintingrequest',
            name='cost',
        ),
    ]
