# Generated by Django 2.2 on 2019-05-22 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_paintingrequest_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingrequest',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paintingrequest',
            name='dateDelivery',
            field=models.DateField(default=datetime.date(2019, 5, 21)),
        ),
    ]
