# Generated by Django 2.2 on 2019-05-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190521_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintingrequest',
            name='dateDelivery',
        ),
    ]
