# Generated by Django 2.2 on 2019-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_paintingrequest_datedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingrequest',
            name='status',
            field=models.CharField(choices=[('C', 'In creation'), ('D', 'Delivered')], max_length=1),
        ),
    ]
