# Generated by Django 2.2.1 on 2019-05-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
