# Generated by Django 2.2.1 on 2019-05-12 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_pedido_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
